using WebStore.CatalogApp.Services;
using Category = WebStore.CatalogDomain.Entities.Category;

namespace WebStore.CatalogTests;

[TestFixture]
public class CategoryServiceTests : BaseTests
{
    private CategoryService _categoryService;

    [SetUp]
    public override void SetUp()
    {
        base.SetUp();

        _categoryService = new CategoryService(_unitOfWork!, _mapper);
    }

    [Test]
    public async Task AddAsync_ShouldCreateCategory_AndTriggerEvent()
    {
        string categoryName = "Electronics";
        bool eventTriggered = false;
        Category? capturedCategory = null;

        CategoryService.CategoryAdded += (cat) =>
        {
            eventTriggered = true;
            capturedCategory = cat;
        };

        int newId = await _categoryService.AddAsync(categoryName, _cts.Token);

        Assert.Multiple(() =>
        {
            Assert.That(newId, Is.GreaterThan(0), "ID should be generated by the repository/DB.");
            Assert.That(eventTriggered, Is.True, "The CategoryAdded event should have fired.");
            Assert.That(capturedCategory?.Name, Is.EqualTo(categoryName));
        });

        CategoryService.CategoryAdded -= (cat) => { };
    }

    [Test]
    public async Task UpdateAsync_ShouldChangeName_WhenCategoryExists()
    {
        int existingId = await _categoryService.AddAsync("Old Name", _cts.Token);
        string newName = "New Name";

        await _categoryService.UpdateAsync(existingId, newName, _cts.Token);

        var updatedCategory = await _categoryService.GetByIdAsync(existingId, _cts.Token);
        Assert.That(updatedCategory.Name, Is.EqualTo(newName));
    }

    [Test]
    public void UpdateAsync_ShouldThrowKeyNotFound_WhenCategoryDoesNotExist()
    {
        int nonExistentId = 9999;

        Assert.ThrowsAsync<KeyNotFoundException>(async () =>
            await _categoryService.UpdateAsync(nonExistentId, "Some Name", _cts.Token));
    }

    [Test]
    public async Task RemoveAsync_ShouldSoftDeleteCategory_AndTriggerEvent()
    {
        int idToRemove = await _categoryService.AddAsync("Soft Delete Me", _cts.Token);
        bool eventTriggered = false;
        CategoryService.CategoryRemoved += (id) => eventTriggered = (id == idToRemove);

        await _categoryService.RemoveAsync(idToRemove, _cts.Token);

        Assert.That(eventTriggered, Is.True, "Event should fire even for soft delete.");

        var resultFromService = await _categoryService.GetByIdAsync(idToRemove, _cts.Token);
        Assert.That(resultFromService, Is.Null, "Service should not return inactive categories.");

        var rawDto = await _unitOfWork!.CategoryRepository.GetByIdAsync(idToRemove, _cts.Token);

        Assert.Multiple(() =>
        {
            Assert.That(rawDto, Is.Not.Null, "Row should still exist in the database.");
            Assert.That(rawDto.Activity.IsActive, Is.False, "IsActive should be false.");
        });
    }
}