//using WebStore.CatalogApp.Services;
//using WebStore.CatalogDomain.Entities;

//namespace WebStore.CatalogTests;

//[TestFixture]
//public class ProductServiceTests : BaseTests
//{
//    private ProductService _productService;

//    [SetUp]
//    public override void SetUp()
//    {
//        base.SetUp();

//        _productService = new ProductService(_unitOfWork!, _mapper, _publishMock!.Object);
//        _unitOfWork!.CategoryRepository.Insert(new CatalogApp.DTOs.Category {Name = "Electronics"});
//        _unitOfWork!.CategoryRepository.Insert(new CatalogApp.DTOs.Category {Name = "Home Appliances"});
//        _unitOfWork.SaveChanges();
//    }

//    [Test]
//    public async Task CreateProductAsync_ShouldSaveToDb_AndReturnValidId()
//    {
//        string name = "Gaming Mouse";
//        decimal price = 59.99m;
//        string description = "High DPI wireless mouse";
//        int stock = 50;
//        int categoryId = 1;

//        int productId = await _productService.CreateProductAsync(name, price, description, stock, categoryId, _cts.Token);

//        Assert.That(productId, Is.GreaterThan(0), "ID should be generated by the repository/DB.");

//        var savedProduct = await _productService.GetProductByIdAsync(productId, _cts.Token);
//        Assert.That(savedProduct, Is.Not.Null, "Product should be saved in the repository/DB.");
//        Assert.That(savedProduct!.Name, Is.EqualTo(name), "Product name should match the input.");
//        Assert.That(savedProduct.Price, Is.EqualTo(price), "Product price should match the input.");
//    }

//    [Test]
//    public async Task UpdateProductPriceAsync_ShouldModifyPrice_AndTriggerEvent()
//    {
//        int id = await _productService.CreateProductAsync("Keyboard", 100m, "Mechanical", 10, 1, _cts.Token);
//        decimal newPrice = 85.50m;


//        await _productService.UpdateProductPriceAsync(id, newPrice, _cts.Token);

//        var product = await _productService.GetProductByIdAsync(id, _cts.Token);
//        Assert.That(product, Is.Not.Null, "Product should exist in the repository/DB.");
//        Assert.That(product!.Price, Is.EqualTo(newPrice), "Product price should be updated.");
//    }

//    [Test]
//    public async Task SearchProductsAsync_ShouldReturnMatchingResults()
//    {
//        await _productService.CreateProductAsync("Apple iPhone", 999m, null, 5, 2, _cts.Token);
//        await _productService.CreateProductAsync("Samsung Galaxy", 899m, null, 5, 1, _cts.Token);
//        await _productService.CreateProductAsync("Apple iPad", 599m, null, 5, 2, _cts.Token);

//        var results = await _productService.SearchProductsAsync("Apple", _cts.Token);

//        Assert.That(results, Has.Exactly(2).Items, "Should return 2 matching products.");
//        Assert.That(results, Has.All.Matches<Product>(p => p.Name.Contains("Apple")), "All results should contain 'Apple' in the name.");
//    }

//    [Test]
//    public async Task DeleteProductAsync_ShouldSoftDeleteProduct_AndTriggerEvent()
//    {
//        int idToRemove = await _productService.CreateProductAsync("Soft Delete Product", 99.99m, "Desc", 10, 1, _cts.Token);

//        await _productService.DeleteProductAsync(idToRemove, _cts.Token);

//        var resultFromService = await _productService.GetProductByIdAsync(idToRemove, _cts.Token);
//        Assert.That(resultFromService, Is.Null, "Service should not return soft-deleted products.");

//        var rawDto = await _unitOfWork!.ProductRepository.GetByIdAsync(idToRemove, _cts.Token);

//        Assert.Multiple(() =>
//        {
//            Assert.That(rawDto, Is.Not.Null, "The record should still exist in the database.");
//            Assert.That(rawDto!.Activity.IsActive, Is.False, "Activity.IsActive should be false after soft delete.");
//        });
//    }

//    [Test]
//    public async Task UpdateProductCategory_ShouldChangeCategory()
//    {
//        int pCat = await _productService.CreateProductAsync("Multi-category Item", 20m, null, 1, 1, _cts.Token);
//        int newCategoryId = 2;
//        await _productService.UpdateProductCategory(pCat, newCategoryId, _cts.Token);

//        var product = await _productService.GetProductByIdAsync(pCat, _cts.Token);
//        Assert.That(product, Is.Not.Null, "Product should exist in the repository/DB.");
//        Assert.That(product!.CategoryId, Is.EqualTo(newCategoryId), "Product category should be updated.");
//    }

//    [Test]
//    public void UpdateProductAsync_ShouldThrowException_WhenIdInvalid()
//    {
//        Assert.ThrowsAsync<KeyNotFoundException>(async () =>
//            await _productService.UpdateProductAsync(9999, "Fake", null, _cts.Token));
//    }
//}