<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
	<PackageReference Include="MassTransit" Version="8.3.6" />
	<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebStore.CatalogDomain\WebStore.CatalogDomain.csproj" />
    <ProjectReference Include="..\WebStore.Contracts\WebStore.Contracts.csproj" />
    <ProjectReference Include="..\WebStore.Shared\WebStore.Shared.csproj" />
  </ItemGroup>

</Project>
