<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-WebStore.BackWorker-299c6eb3-820b-40e7-94e6-b591316d5fbf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CartInfrastructure\WebStore.CartInfrastructure.csproj" />
    <ProjectReference Include="..\WebStore.CartApp\WebStore.CartApp.csproj" />
    <ProjectReference Include="..\Webstore.CatalogService\Webstore.CatalogInfrastructure.csproj" />
    <ProjectReference Include="..\WebStore.Contracts\WebStore.Contracts.csproj" />
    <ProjectReference Include="..\WebStore.NotificationService\WebStore.NotificationService.csproj" />
    <ProjectReference Include="..\WebStore.Shared\WebStore.Shared.csproj" />
    <ProjectReference Include="..\WebStore.UserInfrastructure\WebStore.UserInfrastructure.csproj" />
  </ItemGroup>
</Project>
